version: "2.1"
services:
   web:
      build: .
      ports:
         - "80:4000"
      restart: always
      environment:
         NODE_ENV: production
         PORT: 4000
      links:
         - redis:redis
   flask:
      build: ./flask
      ports:
         - "5000:5000"
      environment:
         - FLASK_APP=app.py
         - FLASK_DEBUG=1
      restart: always
   redis:
      image: "redis:alpine"
      restart: always
