version: "2.1"
services:
   web:
      build: .
      restart: always
      expose:
         - "80"
      environment:
         - NODE_ENV=production
         - VIRTUAL_HOST=propheteer.grantstoltz.com
         - LETSENCRYPT_HOST=propheteer.grantstoltz.com
         - VIRTUAL_PORT=4000
      links:
         - redis:redis
   redis:
      image: "redis:alpine"
      restart: always

networks:
   default:
      external:
         name: nginx-proxy
