version: "2"
services:
   web:
      build: .
      ports:
         - "80:4000"
      restart: always
      environment:
         NODE_ENV: production
         PORT: 4000
      links:
         - redis:redis
   redis:
      image: "redis:alpine"
